# Generated by Django 5.2.4 on 2025-07-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=20)),
                ('expire', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('card_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRE', 'Expired'), ('DECLINED', 'Declined')], default='ACTIVE', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'ordering': ['owner', 'card_number'],
            },
        ),
    ]
