# Generated by Django 5.2.4 on 2025-07-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance on the card', max_digits=16),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='expire',
            field=models.CharField(help_text='Expiration date in MM/YY format (e.g., 12/25)', max_length=5),
        ),
        migrations.AlterField(
            model_name='cards',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='excel_analyzer.cards')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
